gn/urls.py
from pathlib import Path

from rest_framework import routers

from django.conf import settings
from django.conf.urls.static import static as urls_static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from main import api

admin.site.site_header = settings.ADMIN_SITE_HEADER

router = routers.DefaultRouter(trailing_slash=False)
router.register('users', api.UserViewSet)
router.register('comparisons', api.ComparisonViewSet)
router.register('docs', api.DocViewSet)
router.register('files', api.FileViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),

    # login, logout
    path('login', auth_views.LoginView.as_view(next_page='admin'), name='login'),
    path('logout', auth_views.LogoutView.as_view(next_page='/login'), name='logout'),

    path('', include('main.urls', namespace='main')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns.insert(0, path('__debug__/', include(debug_toolbar.urls)))


if settings.LOCAL and settings.DEBUG:
    urlpatterns += urls_static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # serve favicon (remove annoying console errors)
    from django.views import static
    urlpatterns += [
        path(r'favicon.ico',
             static.serve,
             dict(document_root=Path(__file__).parent.joinpath('static', 'images', 'icons'),
                  path='favicon.ico'))
    ]

main/urls.py
from django.urls import path

from . import views


app_name = 'main'


urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

main/models/comparison.py
from django.db import models

from .doc import Doc


class Comparison(models.Model):
    requirements = models.ForeignKey(Doc, related_name='comparisons', on_delete=models.CASCADE)
    application = models.ForeignKey(Doc, related_name='+', on_delete=models.CASCADE)
    results = models.TextField()

    class Meta:
        unique_together = [
            ['requirements', 'application']
        ]

main/models/doc.py
from django.db import models

from .file import File
from .user import User


class Doc(models.Model):
    user = models.ForeignKey(User, related_name='docs', on_delete=models.CASCADE)
    file = models.ForeignKey(File, related_name='docs', on_delete=models.CASCADE)
    name = models.CharField(max_length=25)
    # todo impl validation related to the 'no more than 1 requirement per project' constraint and validation
    is_requirements = models.BooleanField()

    class Meta:
        unique_together = [
            # todo impl validation related to this constraint in serializer
            ['user', 'file', 'is_requirements']
        ]

main/models/file.py
from pathlib import Path

from django.conf import settings
from django.db import models

from .utils.file_field import FileField
from .utils.file_system_storage import FileSystemStorage


storage = FileSystemStorage(location=settings.MEDIA_ROOT)


class File(models.Model):

    file = FileField(unique=True, storage=storage)

    @property
    def path(self):
        return Path(self.file.storage.path(self.file.name))

    @property
    def url(self):
        return self.file.storage.url(self.file.name)

main/models/user.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    class Meta:
        app_label = 'main'

main/views/home.py
import logging

from django.shortcuts import render
from django.views import View

from main.models import User


class HomeView(View):

    def get(self, request):
        logger = logging.getLogger('django')

        logger.error('exemplary home view error log message')
        logger.debug('exemplary home view debug log message')

        context = dict(
            js_data=dict(
                message='Hello World!',
                user_count=User.objects.count(),
            ),
        )

        return render(request, 'main/home.html', context)

gn/templates/base.html
{% load main %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% if settings.LOCAL and settings.DEBUG and False %}
        {% vite_debug %}
    {% else %}
        {% vite_asset 'front/js/main.tsx' %}
        {% vite_asset 'front/css/main.scss' %}
    {% endif %}

    <title>Title</title>

    <script>
        const GN = {{ base_js_data|dict_merge:js_data|json_dumps|safe }};
    </script>
</head>
<body>
    {% block content %}{% endblock %}

    {% csrf_token %}
    <script>
        (function() {
           const tokenEl = document.querySelector('[name=csrfmiddlewaretoken]');
           GN.csrf_token = tokenEl ? tokenEl.value : '';
        }());
    </script>
</body>
</html>

main/templates/main/home.html
{% extends 'base.html' %}

{% block content %}

    {% if request.user.is_anonymous %}
        <a href="{% url 'login' %}">Login</a> (e.g.: demo/demo)<br>
    {% else %}
        <b>Current user:</b> {{ request.user.username }}<br>
        <b>Пример формы:</b><br>
        <form method="POST" action="{% url 'logout' %}">
            {% csrf_token %}
            <button type="submit">Logout</button>
            <input name="next" type="hidden" value="{% url 'main:home' %}">
        </form>
    {% endif %}<br>

    <a href="{% url 'admin:index' %}">Admin</a><br><br>

    <a href="{% url 'api-root' %}">Rest browsable api</a><br><br>

    <br>

    <div data-js-component="hw">
        <div class="spinner">Загрузка...</div>
    </div>

{% endblock %}